<a href="https://colab.research.google.com/github/K4cp3rski/ML_FUW/blob/master/Cybi%C5%84ski_02_zadanie_domowe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Praca domowa I, zadanie II





## Treść

### Wstęp fabularny

Wyobraź sobie, że jesteś pracownikiem w firmie sprzedającej kompleksową usługę tworzenia wizerunków medialnych. Oddział, w którym pracujesz obsługuje ważnego klienta działającego w branży gier i usług cyfrowych.

Twoim zadaniem jest przygotować model uczenia maszynowego, który określać będzie nastawienie emocjonalne postów z Twittera. Zespół odpowiadający za zbieranie danych właśnie dostarczył zestaw danych dla Ciebie.

Do tej pory klasyfikowaniem nastrojów z twittów zajmował się zespół ekspertów. Rozwiązanie takie jest bardzo wolne i drogie, a dokładność ekspertów wynosi tylko 95%. Dlatego zarząd firmy zlecił wdrożenie modelu uczenia maszynowego.

Twój model stanowić będzie jedynie część większego produktu oferowanego przez Twoją firmę. Wyniki Twojego modelu będą bezpośrednio wykorzystywane przez następny zespół, którego zadaniem jest przygotować kolejny model uczenia maszynowego przewidujący reakcje opinii publicznej na posty klienta.

Prace zespołu, który korzystać będzie z Twojego modelu są już bardzo zaawansowane, dlatego nie może on pozwolić sobie na żadne dodatkowe zmiany w swoim projekcie. Absolutnie konieczne jest, aby Twój model przyporządkowywał posty do jednej z trzech klas 'Positive', 'Negative', 'Neutral' lub analogicznych. Posty nie na temat powinny być klasyfikowane jako 'Neutral'.

Notebook z Twoim projektem będzie oglądał Twój szef, więc koniecznie zadbaj, żeby znalazły się w nim najważniejsze przemyślenia, a rysunki były ładne.

Powodzenia 🦾

### Polecenia

1. Wstępna obróbka danych:

 - załaduj zbiór treningowy i testowy,
 - usuń wiersze o brakujących elementach,
 - w kolumnie `sentiment` zamień wartości `'Irrelevant'` na `'Neutral'`.

1. Wykonaj wizualizacje danych:

 - histogram tematów twittów (`entity`),
 - histogram nastawień (`sentiment`),
 - najczęściej padających słów w treści twittów (`content`).

1. Przygotuj dane:

 - przygotuj zbiór cech poprzez wektoryzacje kolumny `content`, 
 - przygotuj etykiety poprzez zakodowanie tekstowych wartości w kolumnie `sentiment` do postaci liczbowej.

  Następnie wytrenuj naiwny model bayesowski. Sprawdź działanie modelu na kilku własnoręcznie napisanych wiadomościach. 

1. Wytrenuj modele:
 - naiwny bayesowski,
 - liniowy SVM,
 - regresji logistycznej,
 - drzewo decyzyjne.

  Sprawdź model na danych treningowych (walidacja krzyżowa) i testowych, następnie wybierz najlepszy model. Uzasadnij swój wybór.
  
1. Zespół ekspertów ręcznie klasyfikuje dane z dokładnością 95%. Porównaj z nimi swój model i napisz jakie są przewagi Twojego modelu.

### Zbiór danych

Zbiór danych został przygotowany na podstawie zbioru [Twitter Sentiment Analysis](https://www.kaggle.com/jp797498e/twitter-entity-sentiment-analysis) i składa się z dwóch plików:
-  `twitter_training.csv` - zbiór treningowy,
- `twitter_validation.csv` - zbiór testowy.

Archiwum z plikami można pobrać z [dysku google](https://drive.google.com/file/d/1sw2vA87fmAI5V5Xl9k-PCSdN5XwydhOB/view?usp=sharing) lub odkomentowując poniższe linie:

In [1]:
import time
start_time = time.time()

In [2]:
# ! pip install gdown
# ! gdown https://drive.google.com/uc?id=1sw2vA87fmAI5V5Xl9k-PCSdN5XwydhOB
# ! unzip twitter.zip

In [45]:
!pip install -U wordcloud
!pip install -U nltk
!pip install -U scikit-learn
!pip install -U pandas
!pip install -U seaborn
!pip install -U numpy

     |████████████████████████████████| 366 kB 14.2 MB/s 
  Attempting uninstall: wordcloud
    Found existing installation: wordcloud 1.5.0
    Uninstalling wordcloud-1.5.0:
      Successfully uninstalled wordcloud-1.5.0
     |████████████████████████████████| 1.5 MB 11.8 MB/s 
     |████████████████████████████████| 749 kB 62.6 MB/s 
  Attempting uninstall: regex
    Found existing installation: regex 2019.12.20
    Uninstalling regex-2019.12.20:
      Successfully uninstalled regex-2019.12.20
  Attempting uninstall: nltk
    Found existing installation: nltk 3.2.5
    Uninstalling nltk-3.2.5:
      Successfully uninstalled nltk-3.2.5


     |████████████████████████████████| 24.8 MB 1.5 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.1
    Uninstalling scikit-learn-1.0.1:
      Successfully uninstalled scikit-learn-1.0.1


     |████████████████████████████████| 11.3 MB 14.1 MB/s 
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.5 which is incompatible.


     |████████████████████████████████| 15.7 MB 15.1 MB/s 
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.3.post1 requires numpy<1.20,>=1.16.0, but you have numpy 1.21.5 which is incompatible.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.5 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


# Rozwiązanie

In [42]:
# Impoty 
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import cross_validate
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from scipy.sparse import hstack

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## Ładowanie danych

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns

import sklearn
print('Zainstalowana wersja scikit-learn: {}.'.format(sklearn.__version__))

import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (20,10) # aby wykresy w Colabie były większe

import numpy as np
from scipy import diag, interp
from itertools import cycle

from sklearn.model_selection import StratifiedKFold, train_test_split, StratifiedShuffleSplit, GridSearchCV
from sklearn import metrics

Zainstalowana wersja scikit-learn: 1.0.1.


In [6]:
train_data = pd.read_csv('twitter_training.csv')
test_data = pd.read_csv('twitter_validation.csv')

Jak widzimy globalnie (Obrazek 1) klasy są w miare zbalansowane, liczebność nie różni się więcej jak 2-krotnie. W związku z tym wydaje się, że nie ma potrzeby sztucznego wyrównywania ich liczebności i można przejść do dalszego etapu preprocessingu danych

## Preprocessing danych

### Zmieniamy labelki na integerowe

In [7]:
# Przydzielamy klasom integerowe labelki

# Neutral = Class 0
train_data.loc[train_data['sentiment'] == 'Positive', 'sentiment'] = 0
# Positive = Class 1
train_data.loc[train_data['sentiment'] == 'Neutral', 'sentiment'] = 1
# Negative = Class 2
train_data.loc[train_data['sentiment'] == 'Negative', 'sentiment'] = 2
# Irrelevant = Class 1
train_data.loc[train_data['sentiment'] == 'Irrelevant', 'sentiment'] = 1

# A teraz to samo dla zbiotu testowego

# Neutral = Class 0
test_data.loc[test_data['sentiment'] == 'Positive', 'sentiment'] = 0
# Positive = Class 1
test_data.loc[test_data['sentiment'] == 'Neutral', 'sentiment'] = 1
# Negative = Class 2
test_data.loc[test_data['sentiment'] == 'Negative', 'sentiment'] = 2
# Irrelevant = Class 1
test_data.loc[test_data['sentiment'] == 'Irrelevant', 'sentiment'] = 1

In [8]:
train_data = train_data.drop(columns='id')
test_data = test_data.drop(columns='id')

train_data = train_data.rename(columns={'sentiment':'Class'})
test_data = test_data.rename(columns={'sentiment':'Class'})

# Pozbywamy się wierszy z niepełnymi informacjani (NaN)
train_data = train_data.dropna(axis='rows', how='all', thresh=int(train_data.shape[1]))
test_data = test_data.dropna(axis='rows', how='all', thresh=int(test_data.shape[1]))

### Wizualizacja danych, oraz najczęściej występujących słów w tweetach danych kategorii

In [9]:
# # Wizualizacja danych

# f = sns.countplot(x='sentiment', data=train_data)
# h = sns.catplot(y='entity', hue='sentiment', data=train_data, kind='count', height=20, aspect=1)
# g = sns.catplot(x='sentiment', col='entity' , col_wrap=4, kind='count', data=train_data, height=4.5, aspect=1.2)
# i = sns.catplot(y='entity', data=train_data, height=20, kind='count')

# (g.set_axis_labels("", "Tweet count")
# .set_xticklabels(["Positive", "Neutral", "Negative", 'Irrelevant'])
# .set_titles("{col_name}")
# .despine(left=True))  

In [10]:
# # Zobaczmy sobie najczęściej występujące słowa w klasach słów pozytywnych, neutralnych, negatywnych i irrelevant

# import wordcloud
# from wordcloud import WordCloud
# import matplotlib.pyplot as plt

# # Neutralne tweety
# neutral_list = list(map(str, train_data [train_data['Class'] == 0]['content']))

# neutral_words = " ".join(neutral_list)
# neutral_plot = WordCloud(width = 512, height = 512).generate(neutral_words)

# # Pozytywne tweety
# positive_list = list(map(str, train_data [train_data['Class'] == 1]['content']))

# positive_words = " ".join(positive_list)
# positive_plot = WordCloud(width = 512, height = 512).generate(positive_words)

# # Negatywne tweety
# negative_list = list(map(str, train_data [train_data['Class'] == 2]['content']))

# negative_words = " ".join(negative_list)
# negative_plot = WordCloud(width = 512, height = 512).generate(negative_words)

# plt.figure(figsize=(10,8))

In [11]:
# images = [neutral_plot, positive_plot, negative_plot]
# image_names = ['neutral', 'positive', 'negative']


# plt.figure(figsize=(20,5))
# plt.suptitle('Most frequent words in tweets class-wise',y = 0.95, x = 0.4, weight='heavy', size='xx-large')
# columns = 4
# for i, image in enumerate(images):
#     plt.subplot(len(images) / columns + 1, columns, i + 1)
#     plt.axis('off')
#     plt.title(image_names[i])
#     plt.imshow(image)

### Rozdzielamy na dane wejściowe i wyjściowe

Po tym zmieniamy komórki ze stringami na floaty za pomocą Vectorizera

In [12]:
from sklearn.model_selection import train_test_split

X_train = train_data.drop(columns='Class')
y_train = np.asarray(train_data['Class']).reshape(-1, 1).ravel()
y_train = y_train.astype('int')

X_test = test_data.drop(columns='Class')
y_test = np.asarray(test_data['Class']).reshape(-1, 1).ravel()
y_test = y_test.astype('int')

### Aby polepszyć wyniki klasyfikatorów poddajemy dane stemmingowi

Jednak jako, że jedna z naszych kolumn zawiera tylko nazwy gier/tematów o których jest pisane, to stemmingowi chcemy poddać jedynie kolumnę z treścią tweetów, bo to tam szukanie słów o wspólnych korzeniach znaczeniowych będzie mieć znaczenie

In [13]:
stemmer = PorterStemmer()
analyzer = CountVectorizer().build_analyzer()

words = stopwords.words("english")
train_data['cleaned'] = train_data['content'].apply(lambda x: " ".join([stemmer.stem(i) for i in re.sub("[^a-zA-Z]", " ", x).split() if i not in words]).lower())
test_data['cleaned'] = test_data['content'].apply(lambda x: " ".join([stemmer.stem(i) for i in re.sub("[^a-zA-Z]", " ", x).split() if i not in words]).lower())

def stemmed_words(doc):
    return (stemmer.stem(w) for w in analyzer(doc))

Teraz jak już mamy zwizualizowane dane i po stemmingu, to przekodujmy je na język zrozumiały przez maszynę, tj. wektory cech.

 W tym celu użyjemy funkcji *TfidfVectorizer*

In [14]:
entities_train = train_data['entity']
contents_train = train_data['cleaned']

entities_test = test_data['entity']
contents_test = test_data['cleaned']

In [15]:
# Dopasowanie i wektoryzowanie dla danych treningowych wraz ze stemmingiem

vectorizer_text =  TfidfVectorizer(min_df= 3, stop_words="english", sublinear_tf=True, norm='l2', ngram_range=(1, 2)) # stwórz instancje obiektu CountVectorizer dla kodowania tekstu tweetów
vectorizer_instances = CountVectorizer() # stwórz instancje obiektu CountVectorizer dla kodowania instancji
entities_train = vectorizer_instances.fit_transform(entities_train) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna instnacji)
contents_train = vectorizer_text.fit_transform(contents_train) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna treści)

X_train = hstack((entities_train, contents_train))

# Wektoryzowanie i przetransformowanie danych testowych korzystając ze słownika stworzonego na bazie danych treningowych

entities_test = vectorizer_instances.transform(entities_test) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna instnacji)
contents_test = vectorizer_text.transform(contents_test) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna treści)

X_test = hstack((entities_test, contents_test))

X_train = hstack((entities_train, contents_train))


In [16]:
print("Dane treningowe: n_samples: %d, n_features: %d" % X_train.shape)

Dane treningowe: n_samples: 73996, n_features: 103542


Odwrotne mapowanie cech na słowa

In [17]:
# # Odwrotne mapowanie tweetów na słowa

# Dla kolumny z tekstem tweetów

feature_names_text = vectorizer_text.get_feature_names_out()
feature_names_text = np.asarray(feature_names_text)

# Dla kolumny z tematami

feature_names_instances = vectorizer_instances.get_feature_names_out()
feature_names_instances = np.asarray(feature_names_instances)


## Naive Bayes

In [18]:
from sklearn.naive_bayes import MultinomialNB

model_NB = MultinomialNB()
model_NB.fit(X_train, y_train)

y_pred = model_NB.predict(X_test)
accur = accuracy_score(y_test, y_pred) # dokładność
print("Dokładność: %0.3f" % accur)
print("Classification report:") # wypisz raport klasyfikacji 
print(classification_report(y_test, y_pred))

print("Macierz błędów") # wypisz macierz (confusion matrix)
print(confusion_matrix(y_test, y_pred))

Dokładność: 0.939
Classification report:
              precision    recall  f1-score   support

           0       0.93      0.92      0.92       277
           1       0.95      0.96      0.95       457
           2       0.93      0.93      0.93       266

    accuracy                           0.94      1000
   macro avg       0.94      0.93      0.94      1000
weighted avg       0.94      0.94      0.94      1000

Macierz błędów
[[254  14   9]
 [ 10 438   9]
 [  9  10 247]]


*** Inspiracja kodem z https://towardsdatascience.com/multi-class-text-classification-with-sklearn-and-nltk-in-python-a-software-engineering-use-case-779d4a28ba5

In [19]:
# instead of doing these steps one at a time, we can use a pipeline to complete them all at once
pipeline = Pipeline([('chi',  SelectKBest(chi2, k=1200)),
                     ('clf', MultinomialNB())])

# fitting our model and save it in a pickle for later use
model_NB = pipeline.fit(X_train, y_train)
with open('Multinomial.pickle', 'wb') as f:
    pickle.dump(model_NB, f)
y_pred = np.array(y_test)

accur = accuracy_score(y_test, y_pred) # dokładność
print("Dokładność: %0.3f" % accur)
print("Classification report:") # wypisz raport klasyfikacji 
print(classification_report(y_test, y_pred))

print("Macierz błędów") # wypisz macierz (confusion matrix)
print(confusion_matrix(y_test, y_pred))

MCC = metrics.matthews_corrcoef(y_test, y_pred)
BACC = metrics.balanced_accuracy_score(y_test, y_pred)
print('MCC =  {m:.3f}, Balanced ACC = {b:.3f}  '.format(m=MCC, b=BACC))

Dokładność: 1.000
Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       277
           1       1.00      1.00      1.00       457
           2       1.00      1.00      1.00       266

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

Macierz błędów
[[277   0   0]
 [  0 457   0]
 [  0   0 266]]
MCC =  1.000, Balanced ACC = 1.000  


## SVM

In [20]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler
model_SVM = LinearSVC(C=1E-2, dual=False, max_iter=10000)

Do SVM już musimy bezwzględnie przeskalować nasze dane

In [21]:
entities_train = train_data['entity']
contents_train = train_data['cleaned']

entities_test = test_data['entity']
contents_test = test_data['cleaned']

# Dopasowanie i wektoryzowanie dla danych treningowych wraz ze stemmingiem

vectorizer_text =  TfidfVectorizer(min_df= 3, stop_words="english", sublinear_tf=True, norm='l2', ngram_range=(1, 2)) # stwórz instancje obiektu CountVectorizer dla kodowania tekstu tweetów
vectorizer_instances = CountVectorizer() # stwórz instancje obiektu CountVectorizer dla kodowania instancji
entities_train = vectorizer_instances.fit_transform(entities_train) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna instnacji)
contents_train = vectorizer_text.fit_transform(contents_train) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna treści)

X_train = hstack((entities_train, contents_train))

# Wektoryzowanie i przetransformowanie danych testowych korzystając ze słownika stworzonego na bazie danych treningowych

entities_test = vectorizer_instances.transform(entities_test) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna instnacji)
contents_test = vectorizer_text.transform(contents_test) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna treści)

X_test = hstack((entities_test, contents_test))


scaler = StandardScaler(with_mean=False)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# <--- !! ---> #



# # Odwrotne mapowanie tweetów na słowa

# Dla kolumny z tekstem tweetów

feature_names_text = vectorizer_text.get_feature_names_out()
feature_names_text = np.asarray(feature_names_text)

# Dla kolumny z tematami

feature_names_instances = vectorizer_instances.get_feature_names_out()
feature_names_instances = np.asarray(feature_names_instances)


In [22]:
# Fitowanie modelu (trwa ok 3 min)

model_SVM.fit(X_train, y_train)

LinearSVC(C=0.01, dual=False, max_iter=10000)

In [23]:
# Walidacja 

from sklearn import metrics

y_pred = model_SVM.predict(X_test)
accur = accuracy_score(y_test, y_pred) # dokładność
print("Dokładność: %0.3f" % accur)
print("Classification report:") # wypisz raport klasyfikacji 
print(classification_report(y_test, y_pred))

print("Macierz błędów") # wypisz macierz (confusion matrix)
print(confusion_matrix(y_test, y_pred))

MCC = metrics.matthews_corrcoef(y_test, y_pred)
BACC = metrics.balanced_accuracy_score(y_test, y_pred)
print('MCC =  {m:.3f}, Balanced ACC = {b:.3f}  '.format(m=MCC, b=BACC))

Dokładność: 0.975
Classification report:
              precision    recall  f1-score   support

           0       0.98      0.96      0.97       277
           1       0.98      0.98      0.98       457
           2       0.97      0.97      0.97       266

    accuracy                           0.97      1000
   macro avg       0.97      0.97      0.97      1000
weighted avg       0.98      0.97      0.97      1000

Macierz błędów
[[267   4   6]
 [  4 450   3]
 [  2   6 258]]
MCC =  0.961, Balanced ACC = 0.973  


Dostajemy bardzo dobry wynik, skuteczność na poziomie 97%

## Regresja Logistyczna

In [41]:
from sklearn.linear_model import LogisticRegression

# Tu znowu model liczy się ok 3 min

# Teraz pewnie z 20 min
model_log = LogisticRegression(solver = 'lbfgs', max_iter=10000, C=0.1)

# W wyniku tego szukania wybrano C=0.1

# grid_values = {'penalty': ['l2'], 'C': [0.1,1,10]}
# model_log = GridSearchCV(model_log, param_grid=grid_values, n_jobs=-1, verbose=4)

model_log.fit(X_train, y_train)

In [25]:
# entities_train = train_data['entity']
# contents_train = train_data['cleaned']

# entities_test = test_data['entity']
# contents_test = test_data['cleaned']

# # Dopasowanie i wektoryzowanie dla danych treningowych wraz ze stemmingiem

# vectorizer_text =  TfidfVectorizer(min_df= 3, stop_words="english", sublinear_tf=True, norm='l2', ngram_range=(1, 2)) # stwórz instancje obiektu CountVectorizer dla kodowania tekstu tweetów
# vectorizer_instances = CountVectorizer() # stwórz instancje obiektu CountVectorizer dla kodowania instancji
# entities_train = vectorizer_instances.fit_transform(entities_train) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna instnacji)
# contents_train = vectorizer_text.fit_transform(contents_train) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna treści)

# X_train = hstack((entities_train, contents_train))

# # Wektoryzowanie i przetransformowanie danych testowych korzystając ze słownika stworzonego na bazie danych treningowych

# entities_test = vectorizer_instances.transform(entities_test) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna instnacji)
# contents_test = vectorizer_text.transform(contents_test) # naucz vectorizer słownika i przetransformuj dane uczące (kolumna treści)

# X_test = hstack((entities_test, contents_test))


# scaler = StandardScaler(with_mean=False)
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)


# # <--- !! ---> #



# # # Odwrotne mapowanie tweetów na słowa

# # Dla kolumny z tekstem tweetów

# feature_names_text = vectorizer_text.get_feature_names_out()
# feature_names_text = np.asarray(feature_names_text)

# # Dla kolumny z tematami

# feature_names_instances = vectorizer_instances.get_feature_names_out()
# feature_names_instances = np.asarray(feature_names_instances)


In [38]:
y_pred = model_log.predict(X_test)  

accur = accuracy_score(y_test, y_pred) # dokładność
print("Dokładność: %0.3f" % accur)
print("Classification report:") # wypisz raport klasyfikacji 
print(classification_report(y_test, y_pred))

print("Macierz błędów") # wypisz macierz (confusion matrix)
print(confusion_matrix(y_test, y_pred))

MCC = metrics.matthews_corrcoef(y_test, y_pred)
BACC = metrics.balanced_accuracy_score(y_test, y_pred)
print('MCC =  {m:.3f}, Balanced ACC = {b:.3f}  '.format(m=MCC, b=BACC))

Dokładność: 0.975
Classification report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       277
           1       0.98      0.98      0.98       457
           2       0.96      0.97      0.97       266

    accuracy                           0.97      1000
   macro avg       0.97      0.97      0.97      1000
weighted avg       0.98      0.97      0.98      1000

Macierz błędów
[[268   3   6]
 [  5 448   4]
 [  3   4 259]]
MCC =  0.961, Balanced ACC = 0.974  


In [44]:
# Cross-Validation

scores = cross_validate(model_log, X_train, y_train, n_jobs=-1, scoring='accuracy', verbose=3)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  3.1min finished


## DecissionTreeClassifier

In [27]:
from sklearn import tree

# Deklarujemy klasyfikator
model_tree = tree.DecisionTreeClassifier()
# Fitujemy do danych treningowych
model_tree = model_tree.fit(X_train, y_train)

In [28]:
# from IPython.display import Image 

# from six import StringIO
# import pydot 

# dot_data = StringIO()  
# tree.export_graphviz(clf, out_file=dot_data,  
                         # class_names=['Neutral', 'Positive', 'Negative'],  
                         # filled=True, rounded=True,  
                         # special_characters=True) 
# graph = pydot.graph_from_dot_data(dot_data.getvalue())  
# Image(graph[0].create_png())



In [29]:
y_pred = model_tree.predict(X_test)  

accur = accuracy_score(y_test, y_pred) # dokładność
print("Dokładność: %0.3f" % accur)
print("Classification report:") # wypisz raport klasyfikacji 
print(classification_report(y_test, y_pred))

print("Macierz błędów") # wypisz macierz (confusion matrix)
print(confusion_matrix(y_test, y_pred))

MCC = metrics.matthews_corrcoef(y_test, y_pred)
BACC = metrics.balanced_accuracy_score(y_test, y_pred)
print('MCC =  {m:.3f}, Balanced ACC = {b:.3f}  '.format(m=MCC, b=BACC))

Dokładność: 0.924
Classification report:
              precision    recall  f1-score   support

           0       0.92      0.90      0.91       277
           1       0.94      0.92      0.93       457
           2       0.89      0.95      0.92       266

    accuracy                           0.92      1000
   macro avg       0.92      0.93      0.92      1000
weighted avg       0.92      0.92      0.92      1000

Macierz błędów
[[249  17  11]
 [ 17 421  19]
 [  4   8 254]]
MCC =  0.883, Balanced ACC = 0.925  


In [30]:
print("Elapsed time\n--- %s seconds ---" % (time.time() - start_time))

Elapsed time
--- 488.72840332984924 seconds ---


Bez CV

Elapsed time
--- 472.361172914505 seconds ---